<?php

if (function_exists('acf_add_local_field_group')):

  acf_add_local_field_group(array(
    'key' => 'group_672672e1d2b83',
    'title' => 'Fields (Project)',
    'fields' => array(
      array(
        'key' => 'field_672673104be28',
        'label' => 'Project Type',
        'name' => 'project_type',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => 'Commercial, Residential, Industrial...',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_672673294be29',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
        'acfe_textarea_code' => 0,
      ),
      array(
        'key' => 'field_6726734b4be2a',
        'label' => 'Downloadable PDF',
        'name' => 'downloadable_pdf',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'uploader' => '',
        'return_format' => 'url',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => 'pdf',
        'library' => 'all',
      ),
      array(
        'key' => 'field_6726737f4be2b',
        'label' => 'Checkmarks',
        'name' => 'checkmarks',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_repeater_stylised_button' => 0,
        'collapsed' => 'field_6726738a4be2c',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Add Item',
        'sub_fields' => array(
          array(
            'key' => 'field_6726738a4be2c',
            'label' => 'Item',
            'name' => 'item',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_672673a94be2d',
        'label' => 'Gallery',
        'name' => 'gallery',
        'type' => 'gallery',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'id',
        'preview_size' => 'large',
        'insert' => 'append',
        'library' => 'all',
        'min' => '',
        'max' => '',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => 'jpg, png',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'project',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_67266ecacd0f5',
    'title' => 'Fields (Team Member)',
    'fields' => array(
      array(
        'key' => 'field_672919b1c697e',
        'label' => 'Profile Picture',
        'name' => 'profile_picture',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'uploader' => '',
        'return_format' => 'id',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'acfe_thumbnail' => 0,
      ),
      array(
        'key' => 'field_67266ee69019f',
        'label' => 'Company Title',
        'name' => 'company_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_67266fcf901a0',
        'label' => 'Languages',
        'name' => 'languages',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_repeater_stylised_button' => 0,
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_67266fff901a1',
            'label' => 'Language',
            'name' => 'language',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'teammember',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_6726552fd5819',
    'title' => 'Fields (Testimonial)',
    'fields' => array(
      array(
        'key' => 'field_6726553b51a3e',
        'label' => 'Review',
        'name' => 'review',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
        'acfe_textarea_code' => 0,
      ),
      array(
        'key' => 'field_6727b0aca4711',
        'label' => 'Profile Picture',
        'name' => 'profile_picture',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'uploader' => '',
        'return_format' => 'id',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'acfe_thumbnail' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'testimonial',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_67264ded74cff',
    'title' => 'Hero Banner (Front Page)',
    'fields' => array(
      array(
        'key' => 'field_6726bcf98c5cd',
        'label' => 'Subtitle',
        'name' => 'subtitle',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_67264e9bea6d3',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_6726bd078c5ce',
        'label' => 'Links',
        'name' => 'links',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_repeater_stylised_button' => 0,
        'collapsed' => 'field_6726bd108c5cf',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Add Link',
        'sub_fields' => array(
          array(
            'key' => 'field_6726bd108c5cf',
            'label' => 'Link',
            'name' => 'link',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
        ),
      ),
      array(
        'key' => 'field_6726bd5f8c5d0',
        'label' => 'Slides',
        'name' => 'slides',
        'type' => 'gallery',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'id',
        'preview_size' => 'medium',
        'insert' => 'append',
        'library' => 'all',
        'min' => 1,
        'max' => 4,
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array(
          'param' => 'page_type',
          'operator' => '==',
          'value' => 'front_page',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_67264ea69b856',
    'title' => 'Hero Banner (Page)',
    'fields' => array(
      array(
        'key' => 'field_67264eac0d0b4',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_6729454f12614',
        'label' => 'Large Content',
        'name' => 'large_content',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
        'acfe_textarea_code' => 0,
      ),
      array(
        'key' => 'field_6729457c12615',
        'label' => 'Small Content',
        'name' => 'small_content',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => '',
        'acfe_textarea_code' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
        array(
          'param' => 'page_type',
          'operator' => '!=',
          'value' => 'front_page',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_672751ed2cf99',
    'title' => 'Theme Footer Settings',
    'fields' => array(
      array(
        'key' => 'field_672751ed31e2b',
        'label' => 'Column 1',
        'name' => 'column_1',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_672752185b69c',
            'label' => 'Logo',
            'name' => 'logo',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'uploader' => '',
            'return_format' => 'id',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'acfe_thumbnail' => 0,
          ),
          array(
            'key' => 'field_6727521f5b69d',
            'label' => 'Content',
            'name' => 'content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'visual',
            'toolbar' => 'full',
            'media_upload' => 0,
            'delay' => 0,
          ),
          array(
            'key' => 'field_672752595b69e',
            'label' => 'Socials',
            'name' => 'socials',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'collapsed' => 'field_672752985b6a0',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Social',
            'sub_fields' => array(
              array(
                'key' => 'field_6727526e5b69f',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'facebook' => 'Facebook',
                  'instagram' => 'Instagram',
                ),
                'default_value' => false,
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
              ),
              array(
                'key' => 'field_672752985b6a0',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => '',
              ),
            ),
          ),
        ),
        'acfe_group_modal_close' => 0,
        'acfe_group_modal_button' => '',
        'acfe_group_modal_size' => 'large',
      ),
      array(
        'key' => 'field_672752b05b6a1',
        'label' => 'Column 2',
        'name' => 'column_2',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_672752bf5b6a7',
            'label' => 'Navigation',
            'name' => 'navigation',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => '',
            'button_label' => '',
            'sub_fields' => array(
              array(
                'key' => 'field_672752c85b6a8',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => '',
              ),
            ),
          ),
        ),
        'acfe_group_modal_close' => 0,
        'acfe_group_modal_button' => '',
        'acfe_group_modal_size' => 'large',
      ),
      array(
        'key' => 'field_672752e15b6a9',
        'label' => 'Column 3',
        'name' => 'column_3',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_672752e15b6aa',
            'label' => 'Navigation',
            'name' => 'navigation',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
              array(
                'key' => 'field_672752e15b6ab',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
              ),
            ),
          ),
        ),
        'acfe_group_modal_close' => 0,
        'acfe_group_modal_button' => '',
        'acfe_group_modal_size' => 'large',
      ),
      array(
        'key' => 'field_672752eb5b6ac',
        'label' => 'Bottom',
        'name' => 'bottom',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'acfe_seamless_style' => 0,
        'acfe_group_modal' => 0,
        'sub_fields' => array(
          array(
            'key' => 'field_6727531d5b6af',
            'label' => 'Navigation',
            'name' => 'navigation',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'collapsed' => 'field_6727532b5b6b0',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Nav Item',
            'sub_fields' => array(
              array(
                'key' => 'field_6727532b5b6b0',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
              ),
            ),
          ),
        ),
        'acfe_group_modal_close' => 0,
        'acfe_group_modal_button' => '',
        'acfe_group_modal_size' => 'large',
      ),
      array(
        'key' => 'field_672751ed31e7b',
        'label' => 'Footer Scripts',
        'name' => 'footer_scripts',
        'type' => 'acfe_code_editor',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'mode' => 'text/html',
        'lines' => 1,
        'indent_unit' => 4,
        'maxlength' => '',
        'rows' => 4,
        'max_rows' => '',
        'return_format' => array(
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-footer',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_672920bb1c571',
    'title' => 'Theme Form Settings',
    'fields' => array(
      array(
        'key' => 'field_672920f578b9d',
        'label' => 'Inquiry Email',
        'name' => 'inquiry_email',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
      array(
        'key' => 'field_6729211678b9e',
        'label' => 'Contact Email',
        'name' => 'contact_email',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-forms',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_6727505e9e875',
    'title' => 'Theme Header Settings',
    'fields' => array(
      array(
        'key' => 'field_67275d38e66f1',
        'label' => 'Logo White',
        'name' => 'logo_white',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'uploader' => '',
        'return_format' => 'id',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => 'png, svg',
        'acfe_thumbnail' => 0,
      ),
      array(
        'key' => 'field_67275d5ae66f2',
        'label' => 'Logo Dark',
        'name' => 'logo_dark',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'uploader' => '',
        'return_format' => 'id',
        'preview_size' => 'medium',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => 'png, svg',
        'acfe_thumbnail' => 0,
      ),
      array(
        'key' => 'field_6727506781d49',
        'label' => 'Navigation',
        'name' => 'navigation',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_repeater_stylised_button' => 0,
        'collapsed' => 'field_6727508281d4a',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Add Nav Item',
        'sub_fields' => array(
          array(
            'key' => 'field_6727508281d4a',
            'label' => 'Link',
            'name' => 'link',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_672750a681d4b',
            'label' => 'Button',
            'name' => 'button',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'primary' => 'Primary',
              'secondary' => 'Secondary',
            ),
            'default_value' => false,
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'placeholder' => '',
            'ajax' => 0,
            'allow_custom' => 0,
            'search_placeholder' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_6727516281d4e',
        'label' => 'Header Scripts',
        'name' => 'header_scripts',
        'type' => 'acfe_code_editor',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'mode' => 'text/html',
        'lines' => 1,
        'indent_unit' => 4,
        'maxlength' => '',
        'rows' => 4,
        'max_rows' => '',
        'return_format' => array(
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-header',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_67264edcd91f0',
    'title' => 'Blocks',
    'fields' => array(
      array(
        'key' => 'field_67264ee74245f',
        'label' => 'Blocks',
        'name' => 'blocks',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_flexible_advanced' => 0,
        'layouts' => array(
          'layout_672650d45661f' => array(
            'key' => 'layout_672650d45661f',
            'name' => 'text',
            'label' => 'Text Columns',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_67279ea067819',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_672779c6cbe98',
                'label' => 'First Column',
                'name' => 'first_column',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
              ),
              array(
                'key' => 'field_672779d6cbe99',
                'label' => 'Second Column',
                'name' => 'second_column',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
              ),
              array(
                'key' => 'field_67279e8e67818',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_67279ecc6781d',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'sub_fields' => array(
                  array(
                    'key' => 'field_67279eaa6781a',
                    'label' => 'Padding Top',
                    'name' => 'padding_top',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                  array(
                    'key' => 'field_67279eb86781b',
                    'label' => 'Padding Bottom',
                    'name' => 'padding_bottom',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                  array(
                    'key' => 'field_67279ec06781c',
                    'label' => 'Anchor',
                    'name' => 'anchor',
                    'type' => 'acfe_slug',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                ),
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
          'layout_672bf72a04706' => array(
            'key' => 'layout_672bf72a04706',
            'name' => 'content',
            'label' => 'Content',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_672bf72a04707',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_672bf72a04709',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
              ),
              array(
                'key' => 'field_672bf72a0470a',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_672bf72a0470b',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'layout' => 'block',
                'acfe_seamless_style' => 0,
                'acfe_group_modal' => 0,
                'acfe_group_modal_close' => 0,
                'acfe_group_modal_button' => '',
                'acfe_group_modal_size' => 'large',
                'sub_fields' => array(
                  array(
                    'key' => 'field_672bf72a0470c',
                    'label' => 'Padding Top',
                    'name' => 'padding_top',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                  array(
                    'key' => 'field_672bf72a0470d',
                    'label' => 'Padding Bottom',
                    'name' => 'padding_bottom',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                  array(
                    'key' => 'field_672bf72a0470e',
                    'label' => 'Anchor',
                    'name' => 'anchor',
                    'type' => 'acfe_slug',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                ),
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
          'layout_6726513e56620' => array(
            'key' => 'layout_6726513e56620',
            'name' => 'image_blocks',
            'label' => 'Image Blocks',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_67279f3967822',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_672a75bfa0e71',
                'label' => 'Blocks',
                'name' => 'blocks',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => 'field_672a75dea0e74',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                  array(
                    'key' => 'field_672a75caa0e72',
                    'label' => 'Background Image',
                    'name' => 'background_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'uploader' => '',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'acfe_thumbnail' => 0,
                  ),
                  array(
                    'key' => 'field_672a75d4a0e73',
                    'label' => 'Subtitle',
                    'name' => 'subtitle',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_672a75dea0e74',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_672a75e3a0e75',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                  ),
                ),
              ),
              array(
                'key' => 'field_67279f4267823',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_67279f4867824',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'field_67279ecc6781d',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
                'acfe_seamless_style' => 0,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
          'layout_67264eef62149' => array(
            'key' => 'layout_67264eef62149',
            'name' => 'slider',
            'label' => 'Slider',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_67279f006781f',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_6727829c445cc',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727877f8ee02',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_672787868ee03',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'acfe_textarea_code' => 0,
              ),
              array(
                'key' => 'field_67277e259012e',
                'label' => 'Slides',
                'name' => 'slides',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => 'field_67277e309012f',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Slide',
                'sub_fields' => array(
                  array(
                    'key' => 'field_67277e309012f',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_67277e3590130',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => 'Prefered aspect-ratio	of 2:3',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'uploader' => '',
                    'return_format' => 'id',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'acfe_thumbnail' => 0,
                  ),
                ),
              ),
              array(
                'key' => 'field_6727987588473',
                'label' => 'Buttons',
                'name' => 'buttons',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Button',
                'sub_fields' => array(
                  array(
                    'key' => 'field_6727987d88474',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_6727988c88475',
                    'label' => 'Type',
                    'name' => 'type',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'primary' => 'Primary',
                      'secondary' => 'Secondary',
                    ),
                    'default_value' => 'primary',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_67279f0b67820',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_67279f1567821',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'field_67279ecc6781d',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
                'acfe_seamless_style' => 0,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
          'layout_67264f3042460' => array(
            'key' => 'layout_67264f3042460',
            'name' => 'projects',
            'label' => 'Projects',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_67279f5867825',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_67279f9267828',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_67279fad67829',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_67279fbc6782a',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'acfe_textarea_code' => 0,
              ),
              array(
                'key' => 'field_6729469dbaf8c',
                'label' => 'Show All',
                'name' => 'show_all',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
              array(
                'key' => 'field_67279fcd6782b',
                'label' => 'Projects',
                'name' => 'projects',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_6729469dbaf8c',
                      'operator' => '!=',
                      'value' => '1',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'post_type' => array(
                  0 => 'project',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 1,
                'return_format' => 'id',
                'save_custom' => 0,
                'save_post_status' => 'publish',
                'acfe_bidirectional' => array(
                  'acfe_bidirectional_enabled' => '0',
                ),
                'ui' => 1,
                'save_post_type' => '',
              ),
              array(
                'key' => 'field_6727a0126782c',
                'label' => 'Buttons',
                'name' => 'buttons',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Button',
                'sub_fields' => array(
                  array(
                    'key' => 'field_6727a0126782d',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_6727a0126782e',
                    'label' => 'Type',
                    'name' => 'type',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'primary' => 'Primary',
                      'secondary' => 'Secondary',
                    ),
                    'default_value' => 'primary',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'placeholder' => '',
                    'search_placeholder' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_67279f5f67826',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_67279f6767827',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'field_67279ecc6781d',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
                'acfe_seamless_style' => 0,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
          'layout_67264f6e42461' => array(
            'key' => 'layout_67264f6e42461',
            'name' => 'testimonials',
            'label' => 'Testimonials',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_6727afbba2d14',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_6727afefa2d17',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727b003a2d18',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727b009a2d19',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'acfe_textarea_code' => 0,
              ),
              array(
                'key' => 'field_6727b02ba2d1d',
                'label' => 'Testimonials',
                'name' => 'testimonials',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'post_type' => array(
                  0 => 'testimonial',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 1,
                'return_format' => 'id',
                'save_custom' => 0,
                'save_post_status' => 'publish',
                'acfe_bidirectional' => array(
                  'acfe_bidirectional_enabled' => '0',
                ),
                'ui' => 1,
                'save_post_type' => '',
              ),
              array(
                'key' => 'field_6727efea99dea',
                'label' => 'Background Image',
                'name' => 'background_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'uploader' => '',
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'acfe_thumbnail' => 0,
              ),
              array(
                'key' => 'field_6727b01da2d1a',
                'label' => 'Buttons',
                'name' => 'buttons',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Button',
                'sub_fields' => array(
                  array(
                    'key' => 'field_6727b01da2d1b',
                    'label' => 'Link',
                    'name' => 'link',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_6727b01da2d1c',
                    'label' => 'Type',
                    'name' => 'type',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'primary' => 'Primary',
                      'secondary' => 'Secondary',
                    ),
                    'default_value' => 'primary',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'placeholder' => '',
                    'search_placeholder' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_6727afc4a2d15',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_6727afd0a2d16',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'field_67279ecc6781d',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
                'acfe_seamless_style' => 0,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
          'layout_67264f7542462' => array(
            'key' => 'layout_67264f7542462',
            'name' => 'team',
            'label' => 'Team',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_6727f22c68978',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_6727f26f6897b',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727f2786897c',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727f27e6897d',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'acfe_textarea_code' => 0,
              ),
              array(
                'key' => 'field_6727f2896897e',
                'label' => 'Team Members',
                'name' => 'team_members',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'post_type' => array(
                  0 => 'teammember',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 1,
                'return_format' => 'id',
                'save_custom' => 0,
                'save_post_status' => 'publish',
                'acfe_bidirectional' => array(
                  'acfe_bidirectional_enabled' => '0',
                ),
                'ui' => 1,
                'save_post_type' => '',
              ),
              array(
                'key' => 'field_6727f23468979',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_6727f23a6897a',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'field_67279ecc6781d',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
                'acfe_seamless_style' => 0,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
          'layout_67264f8042463' => array(
            'key' => 'layout_67264f8042463',
            'name' => 'contact_form',
            'label' => 'Contact Form',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_6727f2e66897f',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_6727f32168982',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727f32968983',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727f39c68985',
                'label' => 'Checkmarks',
                'name' => 'checkmarks',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'collapsed' => 'field_6727f3b268986',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Checkmark',
                'sub_fields' => array(
                  array(
                    'key' => 'field_6727f3b268986',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                ),
              ),
              array(
                'key' => 'field_6727f38f68984',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
                'acfe_textarea_code' => 0,
              ),
              array(
                'key' => 'field_6729203138234',
                'label' => 'Button Text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_6727f44b68988',
                'label' => 'Below Button Text',
                'name' => 'below_button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
              array(
                'key' => 'field_672927b8d5878',
                'label' => 'Background Image',
                'name' => 'background_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'uploader' => '',
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'acfe_thumbnail' => 0,
              ),
              array(
                'key' => 'field_6727f2ec68980',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
              ),
              array(
                'key' => 'field_6727f2f268981',
                'label' => 'Block Settings',
                'name' => 'block_settings',
                'type' => 'clone',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'clone' => array(
                  0 => 'field_67279ecc6781d',
                ),
                'display' => 'seamless',
                'layout' => 'block',
                'prefix_label' => 0,
                'prefix_name' => 0,
                'acfe_seamless_style' => 0,
                'acfe_clone_modal' => 0,
                'acfe_clone_modal_close' => 0,
                'acfe_clone_modal_button' => '',
                'acfe_clone_modal_size' => 'large',
              ),
            ),
            'min' => '',
            'max' => '',
            'acfe_flexible_render_template' => false,
            'acfe_flexible_render_style' => false,
            'acfe_flexible_render_script' => false,
            'acfe_flexible_thumbnail' => false,
            'acfe_flexible_settings' => false,
            'acfe_flexible_settings_size' => 'medium',
            'acfe_flexible_modal_edit_size' => false,
            'acfe_flexible_category' => false,
          ),
        ),
        'button_label' => 'Add Block',
        'min' => '',
        'max' => '',
        'acfe_flexible_stylised_button' => false,
        'acfe_flexible_hide_empty_message' => false,
        'acfe_flexible_empty_message' => '',
        'acfe_flexible_layouts_templates' => false,
        'acfe_flexible_layouts_previews' => false,
        'acfe_flexible_layouts_placeholder' => false,
        'acfe_flexible_layouts_thumbnails' => false,
        'acfe_flexible_layouts_settings' => false,
        'acfe_flexible_async' => array(
        ),
        'acfe_flexible_add_actions' => array(
        ),
        'acfe_flexible_remove_button' => array(
        ),
        'acfe_flexible_layouts_state' => false,
        'acfe_flexible_modal_edit' => array(
          'acfe_flexible_modal_edit_enabled' => false,
          'acfe_flexible_modal_edit_size' => 'large',
        ),
        'acfe_flexible_modal' => array(
          'acfe_flexible_modal_enabled' => false,
          'acfe_flexible_modal_title' => false,
          'acfe_flexible_modal_size' => 'full',
          'acfe_flexible_modal_col' => '4',
          'acfe_flexible_modal_categories' => false,
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
      ),
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'acf-options-footer',
        ),
      ),
    ),
    'menu_order' => 1,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

endif;

?>